import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgspot: {
    height: 90,
    width: 90,
    marginBottom: 90,
  },
  millsong: {
    color: 'white',
    fontSize: 35,
     fontWeight: '700',
  },
  free: {
    color: 'white',
    fontSize: 35,
    fontWeight: '700',
    marginBottom: 90,
  },
  signupfree: {
    flexDirection: 'row',
    backgroundColor: 'green',
    width: wp('80%'),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 19,
    marginBottom: 10,
  },
  textsignupfree: {
    color: 'black',
    fontSize: 17,
    margin: 5,
  fontWeight: '600',
  },
  pressimgphone: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: 'white',
    width: wp('80%'),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 19,
    marginBottom: 10,
    paddingRight: 20,
    paddingLeft: 6,
  },
  imgphone: {
    height: 26,
    width: 26,
    backgroundColor: 'white',
    borderRadius: 50,
    borderColor: 'black',
  },
  textphone: {
    color: 'white',
    fontSize: 17,
    margin: 5,
   fontWeight: '600',
  },
  pressgoogle: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: 'white',
    width: wp('80%'),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 19,
    marginBottom: 10,
    paddingRight: 60,
    paddingLeft: 6,
  },
  imggoogle: {
    color: 'white',
    fontSize: 17,
    margin: 5,
    fontWeight: '600',
  },
  pressfacebook: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: 'white',
    width: wp('80%'),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 19,
    marginBottom: 10,
    paddingRight: 40,
    paddingLeft: 6,
  },
  textface: {
    color: 'white',
    fontSize: 17,
    margin: 5,
    fontWeight: '600',
  },
});
